### ISSUE TITLE
New package is not sync after change of repo name

### ISSUE THREAD

**Issue by jospueyo** [r-universe/jospueyo#1]
I changed my universe repo to jospueyo.r-universe.dev. After that, I added a new package to packages json but this is not syncing with my r-universe site. https://github.com/jospueyo/jospueyo.r-universe.dev/blob/master/packages.json

**Comment by jeroen** [comment]
There is a typo in your packages.json file, making it invalid json (you are missing `{` and `}` for the second package). You can test this by reading the json file in R: `jsonlite::fromJSON("packages.json")`
You can also see this error by clicking the ❌ in your commit CI: https://github.com/jospueyo/jospueyo.r-universe.dev

**Comment by jospueyo** [comment]
Thanks! And apologies for bothering you.
